# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('sat_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('mono_unsat_fat', models.FloatField()),
                ('poly_unsat_fat', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('iron', models.FloatField()),
                ('zinc', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('vit_a', models.FloatField()),
                ('vit_c', models.FloatField()),
                ('thiamin', models.FloatField()),
                ('riboflavin', models.FloatField()),
                ('niacin', models.FloatField()),
                ('vit_b6', models.FloatField()),
                ('folic_acid', models.FloatField()),
                ('vit_b12', models.FloatField()),
                ('vit_d', models.FloatField()),
                ('vit_e', models.FloatField()),
                ('vit_k', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Plan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='incredient',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Vendor'),
        ),
    ]
