# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20160221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='folic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='mono_unsat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='niacin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='poly_unsat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='riboflavin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='thiamin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trans_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vit_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='folic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mono_unsat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='niacin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='poly_unsat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='riboflavin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thiamin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='trans_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vit_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
