# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20160221_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
