# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20160221_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
