# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20160229_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
