from django import forms

class PlanForm(forms.Form):
  name = forms.CharField(label="Plan name:", max_length=150)
  calories = forms.FloatField(label="Calories:")
  fat = forms.FloatField(label="Fat:", required=False)
  # sat_fat = forms.FloatField(label="Saturated Fat:", blank=True)
  # trans_fat = forms.FloatField(label="Trans Fat:", blank=True)
  # mono_unsat_fat = forms.FloatField(label="Monounsaturated Fat:", blank=True)
  # poly_unsat_fat = forms.FloatField(label="Polyunsaturated Fat:", blank=True)
  # carbohydrates = forms.FloatField(label="Carbohydrates:", blank=True)
  # fiber = forms.FloatField(label="Fiber:", blank=True)
  # sugar = forms.FloatField(label="Sugar:", blank=True)
  # protein = forms.FloatField(label="Protein:", blank=True)
  # cholesterol = forms.FloatField(label="Cholesterol:", blank=True)
  # sodium = forms.FloatField(label="Sodium:", blank=True)
  # calcium = forms.FloatField(label="Calcium:", blank=True)
  # magnesium = forms.FloatField(label="Magnesium:", blank=True)
  # potassium = forms.FloatField(label="Potassium:", blank=True)
  # iron = forms.FloatField(label="Iron:", blank=True)
  # zinc = forms.FloatField(label="Zinc:", blank=True)
  # phosphorus = forms.FloatField(label="Phosphorus:", blank=True)
  # vit_a = forms.FloatField(label="Vitamin A:", blank=True)
  # vit_c = forms.FloatField(label="Vitamin C:", blank=True)
  # thiamin = forms.FloatField(label="Thiamin:", blank=True)
  # riboflavin = forms.FloatField(label="Riboflavin:", blank=True)
  # niacin = forms.FloatField(label="Niacin:", blank=True)
  # vit_b6 = forms.FloatField(label="Vitamin B6:", blank=True)
  # folic_acid = forms.FloatField(label="Folic Acid:", blank=True)
  # vit_b12 = forms.FloatField(label="Vitamin B12:", blank=True)
  # vit_d = forms.FloatField(label="Vitamin D:", blank=True)
  # vit_e = forms.FloatField(label="Vitamin E:", blank=True)
  # vit_k = forms.FloatField(label="Vitamin K:", blank=True)