from django import forms

class PlanForm(forms.Form):
  name = forms.CharField(label="Plan name:", max_length=150)
  calories = forms.FloatField(label="Calories:")
  fat = forms.FloatField(label="Fat:", required=False)
  sat_fat = forms.FloatField(label="Saturated Fat:", required=False)
  trans_fat = forms.FloatField(label="Trans Fat:", required=False)
  mono_unsat_fat = forms.FloatField(label="Monounsaturated Fat:", required=False)
  poly_unsat_fat = forms.FloatField(label="Polyunsaturated Fat:", required=False)
  carbohydrates = forms.FloatField(label="Carbohydrates:", required=False)
  fiber = forms.FloatField(label="Fiber:", required=False)
  sugar = forms.FloatField(label="Sugar:", required=False)
  protein = forms.FloatField(label="Protein:", required=False)
  cholesterol = forms.FloatField(label="Cholesterol:", required=False)
  sodium = forms.FloatField(label="Sodium:", required=False)
  calcium = forms.FloatField(label="Calcium:", required=False)
  magnesium = forms.FloatField(label="Magnesium:", required=False)
  potassium = forms.FloatField(label="Potassium:", required=False)
  iron = forms.FloatField(label="Iron:", required=False)
  zinc = forms.FloatField(label="Zinc:", required=False)
  phosphorus = forms.FloatField(label="Phosphorus:", required=False)
  vit_a = forms.FloatField(label="Vitamin A:", required=False)
  vit_c = forms.FloatField(label="Vitamin C:", required=False)
  thiamin = forms.FloatField(label="Thiamin:", required=False)
  riboflavin = forms.FloatField(label="Riboflavin:", required=False)
  niacin = forms.FloatField(label="Niacin:", required=False)
  vit_b6 = forms.FloatField(label="Vitamin B6:", required=False)
  folic_acid = forms.FloatField(label="Folic Acid:", required=False)
  vit_b12 = forms.FloatField(label="Vitamin B12:", required=False)
  vit_d = forms.FloatField(label="Vitamin D:", required=False)
  vit_e = forms.FloatField(label="Vitamin E:", required=False)
  vit_k = forms.FloatField(label="Vitamin K:", required=False)

class PopulateForm(forms.Form):
  terms = forms.CharField(label="Recipe terms:", max_length=150)